---
- name: Install Elasticsearch on host
  hosts: elasticsearch
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install elasticsearch
      apt:
        deb: "https://mirror.yandex.ru/mirrors/elastic/8/pool/main/e/elasticsearch/elasticsearch-8.18.2-amd64.deb"

    - name: Configure Elasticsearch
      block:
        - name: cluster master node
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            regexp: '^cluster\.initial_master_nodes: \["elasticsearch"\]$'
            line: 'cluster.initial_master_nodes: ["{{ ansible_default_ipv4.address }}"]'

        - name: node name
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            line: 'node.name: node-1'
            create: yes

        - name: host name
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            line: 'network.host: 0.0.0.0'
            create: yes

        - name: host port
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            line: 'http.port: 9200'
            create: yes

    - name: daemon_reload
      systemd:
        daemon_reload: true

    - name: Enable and start Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
        state: started
    
- name: Install Kibana on host
  hosts: kibana
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install Kibana
      apt:
        deb: "https://mirror.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-8.18.2-amd64.deb"

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        line: 'server.host: "0.0.0.0"'
        create: yes

    - name: Enable and start Kibana service
      systemd:
        name: kibana
        enabled: yes
        state: started

- name: Install filebeat on nginx hosts
  hosts: web_servers
  become: yes
  tasks:
    
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install filebeat
      apt:
        deb: "https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.18.2-amd64.deb"

    - name: Отключить filestream в конфиге
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '^(- type: filestream|  id: my-filestream-id|    - /var/log/\*\.log|  enabled: false|  paths:)$'
        line: "{{ item }}"
      loop:
        - '#- type: filestream'
        - '  # id: my-filestream-id'
        - '  # - /var/log/*.log'
        - '  # enabled: false'
        - '# paths:'

    - name: Настраиваю входы Filebeat
      blockinfile:
        path: /etc/filebeat/filebeat.yml
        insertafter: '^filebeat.inputs:'
        block: |
          - type: log
            enabled: true
            paths:
              - /var/log/nginx/access.log
              - /var/log/nginx/error.log
          
    - name: Добавить настройку Kibana
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: 'host: "kibana:5601"'
        insertafter: '^setup.kibana:'

    - name: Устанавливаю elasticsearch output
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '^  hosts: \["localhost:9200"\]'
        line: '  hosts: ["https://{{  hostvars["elasticsearch"].ansible_default_ipv4.address  }}:9200"]'

    - name: Configure SSL
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        line: '  ssl.verification_mode: none'
        insertafter: '^  hosts:'
       
    - name: Устанавливаю user
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '^  #username: "elastic"'
        line: '  username: "elastic"'

    - name: Устанавливаю password
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '^  #password: "changeme"'
        line: '  password: "123456"'

    - name: Подключаю модуль nginx
      copy:
        content: |
          - module: nginx
            access:
              enabled: true
              var.paths: ["/var/log/nginx/access.log"]
            error:
              enabled: true
              var.paths: ["/var/log/nginx/error.log"]
        dest: /etc/filebeat/modules.d/nginx.yml

    - name: Перезапускаем filebeat и добавляем в автозагрузку
      service:
        name: filebeat
        state: restarted
        enabled: yes
