---
- name: Установка Zabbix 6 c MySQL и Nginx на Ubuntu 22
  hosts: zabbix
  become: true
  vars:
    zabbix_version: "6.0"
    mysql_root_password: "123456789"
    zabbix_db_password: "123456789"
    # zabbix_server_ip: "192.168.1.1"
    zabbix_server_name: "zabbix"

  tasks:

    - name: Create directory for Zabbix files
      ansible.builtin.file:
        path: /etc/zabbix-files
        state: directory
        mode: "0755"

    - name: Download the Zabbix release package
      ansible.builtin.get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
        dest: /etc/zabbix-files
      become: true

    - name: Install the Zabbix release package
      apt:
        deb: /etc/zabbix-files/zabbix-release_6.0-4+ubuntu22.04_all.deb 
      become: true
  
    - name: Обновление кэша apt
      apt:
        update_cache: yes

    - name: Установка необходимых пакетов
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Установка Python зависимостей для MySQL
      apt:
        name:
          - python3-pip
          - libmysqlclient-dev
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - pkg-config
        state: present

    # - name: Установка mysqlclient для Python 3
    #   pip:
    #     name: mysqlclient
    #     executable: pip3

    - name: Настройка MySQL
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        state: present

    - name: Создание базы данных Zabbix
      mysql_db:
        name: zabbix
        encoding: UTF8
        state: present

    - name: Создание пользователя Zabbix в MySQL
      mysql_user:
        name: zabbix
        password: "{{ zabbix_db_password }}"
        priv: 'zabbix.*:ALL'
        state: present

    - name: Импорт схемы базы данных Zabbix
      command: mysql -u root -p'{{ mysql_root_password }}' zabbix < /usr/share/doc/zabbix-server-mysql/create.sql

    - name: Настройка конфигурационного файла Zabbix
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
        owner: zabbix
        group: zabbix
        mode: '0644'
      notify:
        - restart zabbix-server

    - name: Настройка конфигурационного файла Nginx
      template:
        src: zabbix.conf.j2
        dest: /etc/nginx/conf.d/zabbix.conf
      notify:
        - restart nginx

    - name: Включение необходимых служб
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - zabbix-server
        - nginx
        - mysql

    - name: Открытие необходимых портов
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - 10051
        - 80

  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted
